### ISSUE TITLE
构建失败

### ISSUE THREAD

**Issue by SuperAbee** [aeraki-mesh/meta-protocol-awesomerpc#5]
按照官网教程步骤走，出现以下报错

Bazelisk version: v1.12.2
Starting local Bazel server and connecting to it...
Build label: 5.4.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 15 16:14:25 2022 (1671120865)
Build timestamp: 1671120865
Build timestamp as int: 1671120865
WARNING: Option 'experimental_strict_action_env' is deprecated: Use --incompatible_strict_action_env instead
WARNING: Option 'host_javabase' is deprecated
WARNING: Option 'javabase' is deprecated
ERROR: /data/clareyao/my-protocol-proxy/BUILD:8:16: no such package '@io_istio_proxy//src/envoy/extensions/wasm': BUILD file not found in directory 'src/envoy/extensions/wasm' of external repository @io_istio_proxy. Add a BUILD file to a directory to mark it as a package. and referenced by '//:envoy'
ERROR: Analysis of target '//:envoy' failed; build aborted: Analysis failed
INFO: Elapsed time: 2.345s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (59 packages loaded, 334 targets configured)
    currently loading: @envoy//source/exe ... (12 packages)
    Fetching @meta_protocol_proxy; Cloning 8ac3df9 of https://github.com/aeraki-mesh/meta-protocol-proxy.git

------

环境
Ubuntu: 18.04
bazel: 5.4.0
WORKSPACE: meta-protocol-proxy@tag 1.13

**Comment by zhaohuabing** [comment]
已修复。

https://github.com/aeraki-mesh/meta-protocol-awesomerpc/commit/d31d266cc960e9e54e8e9fdc378d5f22c3f18e07
